# This file was generated by GoReleaser. DO NOT EDIT.
cask "wsectl" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "9de2e4002f5df79bf369f0faa05dbc401e89ce9e19a0abc50fa7f8e7ed0d6883"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff9728e7a096d43d22b36b8c7ec19927019997d04abe7c7ce791af951ba244af"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0eed8cc83d08fdc3a00918bb827847555be8494177139adb1f72f4e46b80f71d"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "64965ffb52536f463e4f1f4099c440ebdda9fc7d6ce52251c0afa7466c49d823"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wsectl"
  desc "Unofficial command-line client for Worksection"
  homepage "https://github.com/pbv7/wsectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wsectl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wsectl"]
    end
  end

  # No zap stanza required

end
