# This file was generated by GoReleaser. DO NOT EDIT.
cask "wsectl" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "d84cdb0e4332e8f954cc699c32b21179d01ec2406bb24790a244f2b259f34591"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "37da9a5b5b0fc0ae0400a64e6ad93b99011999bcc31b607116566a13001f7501"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bafc63bc6cd03f7deb34dc2a37982ec7550fb8cd29069e4052c19fa30de63b34"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e08ecf572bcc44382612d5db836c991f2db6996166e1b92e1f78b45b585b4d75"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wsectl"
  desc "Unofficial command-line client for Worksection"
  homepage "https://github.com/pbv7/wsectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wsectl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wsectl"]
    end
  end

  # No zap stanza required

end
