# This file was generated by GoReleaser. DO NOT EDIT.
cask "wsectl" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "5534fe84e7f278fb7abfce3365eb46f7bc24ad3db3f9bc24a5415636a354f3f3"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8a61f70e8a5cb7f8686d8cdf7da7133e690571388de5f5aa95dbdfb725c9d78b"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d61e36deede7a9b179ac26fb457d39d9def621743d90bd0c36357b67f18ca3b3"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ae00a6402b987a824505afbc06d8543fcbf128ebb41b55fcc5e7c61f0718b356"
      url "https://github.com/pbv7/wsectl/releases/download/v#{version}/wsectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wsectl"
  desc "Unofficial command-line client for Worksection"
  homepage "https://github.com/pbv7/wsectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wsectl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wsectl"]
    end
  end

  # No zap stanza required

end
