# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingheat < Formula
  desc "Network latency heatmap visualizer"
  homepage "https://github.com/pbv7/pingheat"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pbv7/pingheat/releases/download/v0.1.0/pingheat_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "45ba31a5fc44acc76afa4747d5b89c0d42c2b1de8f19149f3827f06375055f4e"

      def install
        bin.install "pingheat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pbv7/pingheat/releases/download/v0.1.0/pingheat_0.1.0_Darwin_arm64.tar.gz"
      sha256 "c7d82797d586f503fad799365cda8fdfeb361a75ad9c9a9c5606b3308bb41f62"

      def install
        bin.install "pingheat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pbv7/pingheat/releases/download/v0.1.0/pingheat_0.1.0_Linux_x86_64.tar.gz"
      sha256 "11362a8f1d50d647fc3ec867e4092258667f2f2ac1ecd5f0596a793bbc98d45f"
      def install
        bin.install "pingheat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pbv7/pingheat/releases/download/v0.1.0/pingheat_0.1.0_Linux_arm64.tar.gz"
      sha256 "68230909051c66f9db6883d31ea79d21ab511fc885b0458159f84e5fc3fc3e84"
      def install
        bin.install "pingheat"
      end
    end
  end

  test do
    system "#{bin}/pingheat", "--version"
  end
end
