# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingheat < Formula
  desc "Network latency heatmap visualizer"
  homepage "https://github.com/pbv7/pingheat"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pbv7/pingheat/releases/download/v0.2.0/pingheat_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "46a5c316e23e981afcb256d1bfba162f1f2612e644275ca94b2609a697b5a65f"

      def install
        bin.install "pingheat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pbv7/pingheat/releases/download/v0.2.0/pingheat_0.2.0_Darwin_arm64.tar.gz"
      sha256 "f80698dbf5391812fb0a4835ebd9576f67e13e0e5e84e11a844873cb59809cb3"

      def install
        bin.install "pingheat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pbv7/pingheat/releases/download/v0.2.0/pingheat_0.2.0_Linux_x86_64.tar.gz"
      sha256 "21b02060ff78561ee9cae04d1a935b71b75e6d7a171417eb43387a1c8733da0d"
      def install
        bin.install "pingheat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pbv7/pingheat/releases/download/v0.2.0/pingheat_0.2.0_Linux_arm64.tar.gz"
      sha256 "be586cf71a303123b03e5135c77e40bd7cc0cac07848504bae085280187185f6"
      def install
        bin.install "pingheat"
      end
    end
  end

  test do
    system "#{bin}/pingheat", "--version"
  end
end
