# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pingheat < Formula
  desc "Network latency heatmap visualizer"
  homepage "https://github.com/pbv7/pingheat"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pbv7/pingheat/releases/download/v0.1.1/pingheat_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "a27f2dfbdb7b416bc8d41fe992871bbf44e0e1d113297555eba77753eb260b29"

      def install
        bin.install "pingheat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pbv7/pingheat/releases/download/v0.1.1/pingheat_0.1.1_Darwin_arm64.tar.gz"
      sha256 "47bf92ae94d3c1fdacfae83c77da2e3df1ffe5db61aa0054e01ff7434ec751fe"

      def install
        bin.install "pingheat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pbv7/pingheat/releases/download/v0.1.1/pingheat_0.1.1_Linux_x86_64.tar.gz"
      sha256 "64d1131035b865f67d0e845dfd2750344da425c2f045635dbc193cbcd3263d45"
      def install
        bin.install "pingheat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pbv7/pingheat/releases/download/v0.1.1/pingheat_0.1.1_Linux_arm64.tar.gz"
      sha256 "22fb27080cc173d5cdb66b22fa4c2af3e5ae75833cda6cdb672276158afc0cb4"
      def install
        bin.install "pingheat"
      end
    end
  end

  test do
    system "#{bin}/pingheat", "--version"
  end
end
